CFLAGS = -I../ -I../Theming

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ReachAppFakePhoneMode
ReachAppFakePhoneMode_FILES = Tweak.x
ReachAppFakePhoneMode_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk
