CFLAGS = -I../ -I../Theming -O2

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ReachAppFakePhoneMode
ReachAppFakePhoneMode_FILES = Tweak.xm
ReachAppFakePhoneMode_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk
