export TARGET = iphone:9.2

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MultiplexerTutorial
MultiplexerTutorial_FILES = Tweak.xm
MultiplexerTutorial_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
