CFLAGS = -fno-objc-arc -O2

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ReachAppAssertiondHooks
ReachAppAssertiondHooks_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
